blank_issues_enabled: true
contact_links:
  - name: "✉️ E-Mail (Fallback)"
    url: "mailto:seipa.flyer918@simplelogin.com"
    about: "Falls du kein GitHub-Konto hast. / If you don't have a GitHub account."
