name: "💬 Frage / Question"
description: "Frage zum Experiment oder zum Angebot. / Question about the experiment or the service."
title: "[Frage] "
labels: ["frage"]
body:
  - type: textarea
    id: frage
    attributes:
      label: "Deine Frage / Your question"
    validations:
      required: true
